#pragma once

#define COG2D_NAMESPACE_BEGIN_DECL namespace cog2d {
#define COG2D_NAMESPACE_END_DECL \
	}                            \
	;
#define COG2D_NAMESPACE_BEGIN_IMPL COG2D_NAMESPACE_BEGIN_DECL
#define COG2D_NAMESPACE_END_IMPL COG2D_NAMESPACE_END_DECL
