function(cog2d_add_game _name)
	add_executable(${_name} ${ARGN})
	target_link_libraries(${_name} PRIVATE cog2d)
endfunction()

function(cog2d_unity_group_sources _target)
	set_target_properties(${_target} PROPERTIES UNITY_BUILD_MODE GROUP)
	get_target_property(_target_sources ${_target} SOURCES)
	set_source_files_properties(${_target_sources} PROPERTIES UNITY_GROUP "${_target}_sources")
	get_target_property(_cog2d_sources cog2d INTERFACE_SOURCES)
	set_source_files_properties(${_cog2d_sources} PROPERTIES UNITY_GROUP "cog2d_sources")
endfunction()
